version: "2"
build:
  commands:
    - npm install
    - npm run build
    - echo "Build completed successfully"
start:
  command: npm run preview -- --host 0.0.0.0 --port $PORT
env:
  NODE_ENV: production
